---

- name: Install systemd unit
  become: True
  template:
    src: taskmanager.service.j2
    dest: /etc/systemd/system/taskmanager.service
    mode: 0644
  register: taskmanager_service_installed

- name: Launch Flink TaskManager
  become: True
  systemd:
    name: taskmanager
    state: started
    daemon_reload: True
    enabled: '{{ enable_services }}'
  when: taskmanager_service_installed.changed
